### ISSUE TITLE
Module is not install able on odoo 9

### ISSUE THREAD

**Issue by awaistune** [Asmaa-Aly/hr_annual_leave#1]
me using windows and trying to install hr_annual_leave module and getting this error.

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\http.py", line 643, in _handle_exception
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\http.py", line 680, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\http.py", line 316, in _call_function
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\http.py", line 309, in checked_call
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\http.py", line 959, in __call__
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\http.py", line 509, in response_wrap
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server\openerp\addons\web\controllers\main.py", line 896, in call_button
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server\openerp\addons\web\controllers\main.py", line 884, in _call_kw
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server\openerp\addons\base\module\module.py", line 459, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server\openerp\addons\base\module\module.py", line 533, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\modules\registry.py", line 386, in new
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\modules\loading.py", line 338, in load_modules
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\modules\loading.py", line 237, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\modules\loading.py", line 156, in load_module_graph
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\modules\loading.py", line 98, in _load_data
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\tools\convert.py", line 851, in convert_file
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\tools\convert.py", line 938, in convert_xml_import
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\tools\convert.py", line 801, in parse
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\tools\convert.py", line 804, in parse
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\tools\convert.py", line 503, in _tag_menuitem
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\tools\convert.py", line 782, in id_get
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\tools\convert.py", line 793, in model_id_get
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server\openerp\addons\base\ir\ir_model.py", line 982, in xmlid_to_res_model_res_id
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\api.py", line 250, in wrapper
  File "<string>", line 2, in xmlid_lookup
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server.\openerp\tools\cache.py", line 85, in lookup
  File "C:\Program Files (x86)\Odoo 9.0-20160410\server\openerp\addons\base\ir\ir_model.py", line 972, in xmlid_lookup
ParseError: "External ID not found in the system: hr.menu_hr_configuration" while parsing file:///C:/Program%20Files%20(x86)/Odoo%209.0-20160410/server/openerp/addons/hr_annual_leave/views/hr_annual_leave_view.xml:6, near
<menuitem name="Configure Annual Leaves" action="action_hr_annual_leave" id="menu_hr_annual_leave" parent="hr.menu_hr_configuration" sequence="10"/>

Thanks in advance for help

**Comment by Asmaa-Aly** [comment]
this module on odoo 8
